from app.routers import (
    activity,
    admin,
    auth,
    finance,
    health,
    intake,
    manager,
    me,
    meta,
    notifications,
    policy,
    reports,
    sheets,
)

ALL_ROUTERS = [
    health.router,
    auth.router,
    sheets.router,
    manager.router,
    finance.router,
    policy.router,
    admin.router,
    meta.router,
    reports.router,
    intake.router,
    activity.router,
    notifications.router,
    me.router,
]
